export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const FETCH_DATA = "FETCH_DATA";
export const BAD_RESPONSE_LINK = "BAD_RESPONSE_LINK";
